collections:
  articles:
    output: true
    permalink: /articles/:name.html
  categories:
    output: true
    permalink: /categories/:path.html

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
      category: Uncategorized
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "page"

title: Site Stacker Documentation

kramdown:
  input: GFM
  hard_wrap: false # this should be removed (default is true) to work the same as on GitHub Pages

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - octopress-debugger
